### ISSUE TITLE
Create readme.md 

### ISSUE THREAD

**Issue by bdravec** [PythonDataScience24/AirBnB-DataScienceProject#1]
Welcome to this Project
Project Description
Project Vision
Project Goals
Project Target Group: Why is this important for who?
Links to "how to contribute" / "how to get involved"
License information OSS?

**Comment by TheRBen12** [comment]
[Lecture8_managingcodingproject.pdf](https://github.com/VioCamill/Data-Science-Project/files/15078511/Lecture8_managingcodingproject.pdf)
