### ISSUE TITLE
Add doc string to methods

### ISSUE THREAD

**Issue by TheRBen12** [PythonDataScience24/AirBnB-DataScienceProject#18]
Doc string and comments are still missing, they need to be added

**"Steckenpfermethode" als gutes Beispiel**
neighbourhood_visualizer
Z90 visualize_availability_when_price_is....( )

**Comment by Wii42** [comment]
Docstring conventions: https://peps.python.org/pep-0257/
How to specify return type / parameters: https://stackoverflow.com/questions/45004725/how-to-specify-different-return-types-in-python-docstring
