### ISSUE TITLE
provide visualizations for Airbnb's

### ISSUE THREAD

**Issue by TheRBen12** [PythonDataScience24/AirBnB-DataScienceProject#23]
As the third task needs to be implemented, visualizations need to provided. 
Visualizations are provided, after a user has selected a neighborhood.
For the overview, no visualizations are provided, as they are not needed for the overview. 

**Acceptance criteria**

- [ ] As for a selected neighborhood information about prices / costs, availability, and rating are provided, 
provide for each topic at least one visualization. 

- [ ] Create a visualization about room type distribution
- [ ] availability_plotter.py (Romano) / price_plotter.py (Lukas) / rating_plotter.py (Viola & Babs)
- [ ] no plots should be created in the neighbourhood_visualizer.py
- [ ] everybody inserts their plot into the neighbourhood_visualiyer.py

**Questions**
- how does Streamlit support plots?
-

**Comment by bdravec** [comment]
import streamlit as st
import matplotlib.pyplot as plt
import numpy as np

arr = np.random.normal(1, 1, size=100)
fig, ax = plt.subplots()
ax.hist(arr, bins=20)

st.pyplot(fig)
