### ISSUE TITLE
Implement a unit test

### ISSUE THREAD

**Issue by TheRBen12** [PythonDataScience24/AirBnB-DataScienceProject#25]
Implement a unit test with **_at least four test_** cases
Suggestion for a class: ideally , it should be tested with a mock data frame. availability testfall e.g. availability - 1, > 365

**Acceptance criteria**
- init fct using a mock data frame test_df
- import unit test module into test file only
- for the unit tests a separated file is provided.
- Write a unit test that tests a function in your code that could produce an unexpected output.
- Provide a description of how this function might produce an unexpected result and how you
tested it in a "testing.md" file.

Question:
- [ ] do we need to use the unit test module from python?

**Comment by Wii42** [comment]
Documentation: https://docs.streamlit.io/develop/api-reference/charts/st.pyplot

**Comment by bdravec** [comment]
tests/neighbourhood_selector_test.py

**Comment by TheRBen12** [comment]
is this issue completed?

**Comment by bdravec** [comment]
> is this issue completed?

yes, I've just updated the TESTING.md file

**Comment by bdravec** [comment]
done
