### ISSUE TITLE
Provide feedback to another group in the form of an issue on their project

### ISSUE THREAD

**Issue by TheRBen12** [PythonDataScience24/AirBnB-DataScienceProject#26]
Look at the code of a project from another group and identify something you think could be
improved. It could be a bug that you find, suggestions for restructuring/improving the code,
or new features you think would enhance the project.
Open an issue on that project describing what you think could be improved or fixed. Please make sure there is not another similar issue already open.
Each group member needs to submit an issue on another group's project.

**Comment by bdravec** [comment]
issue submitted to Bp project https://github.com/PythonDataScience24/Bb/issues

**Comment by VioCamill** [comment]
issue submitted to fitness-tracker https://github.com/PythonDataScience24/fitness-tracker/issues/1

**Comment by Wii42** [comment]
issue submitted to Music-Player https://github.com/PythonDataScience24/Music-Player/issues/4

**Comment by TheRBen12** [comment]
issues submitted to https://github.com/PythonDataScience24/fitness-tracker/
