### ISSUE TITLE
Visualize the number of rooms for all neighborhood group

### ISSUE THREAD

**Issue by bdravec** [PythonDataScience24/AirBnB-DataScienceProject#27]
To visualize the room type in the neighbourhood, **_we only plot it if there's no room type selected._** 

- [ ] Implement a visualization **_visualizing the number of rooms for all neighborhood group_**.
- [ ] create a class neighbourhood_plot_visualizer.py

**Comment by TheRBen12** [comment]
See pushed code, if you have any upcoming ideas, please let me know
