### ISSUE TITLE
remove options with 0 possibilities 

### ISSUE THREAD

**Issue by Learn5Code** [PythonDataScience24/AirBnB-DataScienceProject#29]
# Main issue:
When selecting the options for a certain air bnb. it can be the case, that i eliminate all airbnbs with the filters. You could make it in a way, so you don't can select these filters. (Or change the color of these options for example to gray.)

# Example: 
* Neighbourhood Group:
  * Brooklyn
* Neighbourhood:
  * Kensington
* Room Type:
  * Hotel room

Like this I have 0 possible rooms. So why should this even be an option? (or you could write the option in a gray tone so i can see that it has 0 rooms like this but i could still choose it.)

**Comment by bdravec** [comment]
@Learn5Code thanks for trying out our 'Airbnb - DataScienceProject' - we appreciate your feedback and the detailed case description. This is very helpful to us and we will keep you posted on our progress to make this a better user experience for you. So long and thanks again, your Airbnb-DataScienceProject Team

**Comment by bdravec** [comment]
@Learn5Code thanks again for pointing this out - after careful revision we decided to implement a slightly different solution so the user can still do her search but will be made aware that there's currently no listing available for her selection and to pls adjust the selection.
