### ISSUE TITLE
Provide detailed instructions

### ISSUE THREAD

**Issue by marcinebessire** [PythonDataScience24/AirBnB-DataScienceProject#30]
In home.py, when the data file 'Airbnb_Open_processed_Data.csv' is missing the error is massed is helpful. But there are no instructions of feedback for the user when the Dataframe is empty [or when a selections returns no data](https://github.com/PythonDataScience24/AirBnB-DataScienceProject/issues/29). This may lead to confusions... 

Maybe provide a clear massage or instruction when the Dataframe is empty or when a selections gives no data. 
E.g. display message like "No listing matches you selection. Please try a different criteria"

**Comment by bdravec** [comment]
@marcinebessire many thanks for trying our app 'Airbnb' - your feedback is very helpful and important to us. We'll let you know when we've implemented your request. Kindest regards, the Airbnb DataScienceProject :-)

**Comment by bdravec** [comment]
https://github.com/PythonDataScience24/AirBnB-DataScienceProject/issues/30 is already stated in #29

**Comment by bdravec** [comment]
@marcinebessire thanks again for pointing this out - we've adjusted the error message and hope it's clearer for the user now. Kindest regards, the Airbnb team
